/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /** Submit Job */
        post: operations["submit_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Job */
        post: operations["resume_job_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Job Events */
        get: operations["stream_job_events_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video */
        get: operations["get_video_jobs__job_id__video_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/subtitles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subtitles */
        get: operations["get_subtitles_jobs__job_id__subtitles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/segments/{index}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Segment Audio */
        get: operations["get_segment_audio_jobs__job_id__segments__index__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/segments/{index}/clip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Segment Clip */
        get: operations["get_segment_clip_jobs__job_id__segments__index__clip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/segments/{index}/scene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Segment Scene */
        get: operations["get_segment_scene_jobs__job_id__segments__index__scene_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/scorm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scorm Package */
        get: operations["get_scorm_package_jobs__job_id__scorm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Importance
         * @description How much a segment matters, 1 (aside) to 5 (the point of the video).
         * @enum {integer}
         */
        Importance: 1 | 2 | 3 | 4 | 5;
        /**
         * JobStatus
         * @description Where a job is. ``FAILED`` is terminal only until T22 resumes it from its checkpoint.
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /** JobSubmission */
        JobSubmission: {
            /** Topic */
            topic: string;
            /**
             * Target Duration Ms
             * @default 420000
             */
            target_duration_ms: number;
        };
        /**
         * Segment
         * @description A segment as the pipeline knows it: the plan, plus everything measured since.
         *
         *     The nullable fields fill in stages, and the order is load-bearing. ``narration`` arrives
         *     from the scripting node, ``duration_ms`` from the TTS adapter *measuring the audio it just
         *     wrote*, and only then can ``tier`` be assigned and ``scene`` authored against a real
         *     duration.
         *
         *     That ordering is Invariant 1, and it is why this is a separate class rather than
         *     ``SegmentPlan`` with more fields: a combined model would show the LLM a ``duration_ms``
         *     field it is forbidden to fill, leaving the rule to be enforced by prompt wording. Here the
         *     model never sees the field at all.
         */
        Segment: {
            /**
             * Index
             * @description Position in the video, from 0.
             */
            index: number;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            visual_intent: components["schemas"]["VisualIntent"];
            importance: components["schemas"]["Importance"];
            /**
             * Narration
             * @description The spoken script for this segment, written by T15.
             */
            narration?: string | null;
            /**
             * Duration Ms
             * @description Measured length of the narration audio, in milliseconds. Set only by a TTSProvider from the file it wrote -- never estimated, never from a word count.
             */
            duration_ms?: number | null;
            /**
             * Word Marks
             * @description T18A: per-word timing within this segment's narration audio, filled at the same stage as duration_ms. May be empty -- not every TTSProvider reports word boundaries; consumers must degrade to an even stagger rather than assume this is set.
             */
            word_marks?: components["schemas"]["WordMark"][];
            /** @description Assigned by core/tier_resolver.py, once duration_ms is known. */
            tier?: components["schemas"]["Tier"] | null;
            /**
             * Scene
             * @description This segment's composed scene: a layout plus the blocks that fill it. Untyped here for the same reason `slots` was before it -- the shape is progressive (core/graph/nodes/visual_plan.py writes it with each block's payload still null, core/graph/nodes/scene_author.py fills them in) and varies with the layout/block choice, which the LLM makes per video rather than per intent now. Validate with core.scene_schemas.ComposedScene at the point of use.
             */
            scene?: {
                [key: string]: unknown;
            } | null;
            /**
             * Clip Key
             * @description Storage key of this segment's final clip (rendered video + narration audio, muxed). Set only by core/graph/nodes/render_scene.py, once slots are filled.
             */
            clip_key?: string | null;
        };
        /**
         * Tier
         * @description How richly a segment is rendered, and therefore what it costs in frames.
         *
         *     ``IntEnum`` because the tier resolver compares and sums these, and a checkpointed job
         *     serialises them as 0/1/2. The names say what happens; the values are the tier numbers used
         *     everywhere else. Capture method per tier is in the ``scene-templates`` skill.
         * @enum {integer}
         */
        Tier: 0 | 1 | 2;
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VideoJob
         * @description One video request, and everything the pipeline has learned about it.
         *
         *     Serves as pipeline state, as the LangGraph checkpoint payload (T14), and as the API
         *     response body (T19) -- hence a plain model with defaults rather than a strict schema.
         *     Extras are forbidden all the same: pydantic ignores an unknown key by default, so a typo in
         *     a request body would be dropped in silence rather than rejected.
         */
        VideoJob: {
            /** Job Id */
            job_id: string;
            /**
             * Topic
             * @description The prompt as the user typed it.
             */
            topic: string;
            /**
             * Target Duration Ms
             * @default 420000
             */
            target_duration_ms: number;
            /** @default queued */
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Segments */
            segments?: components["schemas"]["Segment"][];
            /**
             * Video Key
             * @description Storage key of the finished, concatenated video. Set only by core/graph/nodes/finalize.py, once every segment's clip has been rendered and muxed.
             */
            video_key?: string | null;
            /**
             * Subtitles Key
             * @description T18A: storage key of the SRT sidecar (mux/subtitles.py). Set alongside video_key by core/graph/nodes/finalize.py. May stay null on the same terms as an individual segment's word_marks -- nothing downstream requires it.
             */
            subtitles_key?: string | null;
            /**
             * Error
             * @description T24: why this job is FAILED, truncated to 500 chars. Set only by api/runner.py from the caught exception's str(); cleared on resume (api/jobs.py) so a retried job never displays a stale reason.
             */
            error?: string | null;
        };
        /**
         * VisualIntent
         * @description What a segment's visual is for. Closed by design.
         * @enum {string}
         */
        VisualIntent: "title_card" | "bullet_list" | "comparison" | "diagram_flow" | "code_walkthrough" | "stat_callout";
        /**
         * WordMark
         * @description One spoken word, and when it landed in its segment's narration audio.
         *
         *     T18A: what makes a caption or an on-screen reveal track the actual voice instead of an
         *     evenly-spaced guess. Contract vocabulary, not a domain concept -- same precedent as
         *     ``SkillPack``/``QueuedJob`` living beside the interface they belong to rather than in
         *     ``core/`` (D22's boundary runs one way: ``core`` may import ``interfaces``, never the
         *     reverse). ``offset_ms``/``duration_ms`` are relative to the *start of this segment's own
         *     audio*, not the final concatenated video.
         */
        WordMark: {
            /** Text */
            text: string;
            /** Offset Ms */
            offset_ms: number;
            /** Duration Ms */
            duration_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoJob"][];
                };
            };
        };
    };
    submit_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_job_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_job_events_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_jobs__job_id__video_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subtitles_jobs__job_id__subtitles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segment_audio_jobs__job_id__segments__index__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segment_clip_jobs__job_id__segments__index__clip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segment_scene_jobs__job_id__segments__index__scene_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scorm_package_jobs__job_id__scorm_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
